export const CUISINE_TYPES = [
  "Sri Lankan",
  "Chinese",
  "Italian",
  "Indian",
  "Japanese",
  "Seafood",
  "Continental",
  "BBQ & Grill",
  "Thai",
  "Middle Eastern",
  "Fusion",
  "Desserts & Cafe",
];

export const PRICE_RANGES = [
  "BUDGET",
  "MODERATE",
  "EXPENSIVE",
  "FINE_DINING",
] as const;

export const DIETARY_TAGS = [
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Halal",
  "Dairy-Free",
  "Nut-Free",
  "Spicy",
  "Low-Calorie",
];

export const MENU_CATEGORIES = {
  "Sri Lankan": [
    "Rice & Curry",
    "Short Eats",
    "Kottu",
    "Hoppers",
    "Soups",
    "Desserts",
    "Beverages",
  ],
  Chinese: [
    "Dim Sum",
    "Noodles",
    "Rice",
    "Soups",
    "Seafood",
    "Vegetarian",
    "Beverages",
  ],
  Italian: [
    "Antipasti",
    "Pasta",
    "Pizza",
    "Risotto",
    "Mains",
    "Desserts",
    "Beverages",
  ],
  Indian: [
    "Starters",
    "Curries",
    "Biryani",
    "Breads",
    "Tandoor",
    "Desserts",
    "Beverages",
  ],
  Japanese: [
    "Sushi",
    "Sashimi",
    "Ramen",
    "Tempura",
    "Teppanyaki",
    "Desserts",
    "Beverages",
  ],
  Seafood: [
    "Starters",
    "Crab",
    "Prawns",
    "Fish",
    "Lobster",
    "Grilled",
    "Beverages",
  ],
  Continental: [
    "Starters",
    "Soups",
    "Salads",
    "Mains",
    "Steaks",
    "Desserts",
    "Beverages",
  ],
  "BBQ & Grill": [
    "Starters",
    "Chicken",
    "Beef",
    "Pork",
    "Lamb",
    "Sides",
    "Beverages",
  ],
  Thai: [
    "Starters",
    "Soups",
    "Curries",
    "Stir Fry",
    "Noodles",
    "Desserts",
    "Beverages",
  ],
  "Middle Eastern": [
    "Mezze",
    "Grills",
    "Kebabs",
    "Rice",
    "Breads",
    "Desserts",
    "Beverages",
  ],
  Fusion: [
    "Small Plates",
    "Sharing",
    "Mains",
    "Desserts",
    "Cocktails",
    "Beverages",
  ],
  "Desserts & Cafe": [
    "Cakes",
    "Ice Cream",
    "Waffles",
    "Hot Drinks",
    "Cold Drinks",
    "Light Meals",
  ],
};

export const MENU_ITEMS: Record<
  string,
  {
    name: string;
    desc: string;
    priceMin: number;
    priceMax: number;
    category: string;
    dietary: string[];
  }[]
> = {
  "Sri Lankan": [
    {
      name: "Rice & Curry (Veg)",
      desc: "Steamed basmati rice with 5 vegetable curries, papad, and chutney",
      priceMin: 350,
      priceMax: 650,
      category: "Rice & Curry",
      dietary: ["Vegetarian", "Halal"],
    },
    {
      name: "Rice & Curry (Fish)",
      desc: "Steamed rice with fish curry, dhal, mallum, and three vegetable sides",
      priceMin: 450,
      priceMax: 850,
      category: "Rice & Curry",
      dietary: ["Halal"],
    },
    {
      name: "Chicken Kottu",
      desc: "Shredded roti stir-fried with chicken, egg, leeks, and spices on a hot griddle",
      priceMin: 500,
      priceMax: 950,
      category: "Kottu",
      dietary: ["Halal"],
    },
    {
      name: "Cheese Kottu",
      desc: "Shredded roti with melted cheese, egg, and vegetables",
      priceMin: 550,
      priceMax: 1000,
      category: "Kottu",
      dietary: ["Vegetarian"],
    },
    {
      name: "Egg Hoppers",
      desc: "Bowl-shaped rice flour hoppers with a soft egg in the centre, served with coconut sambol",
      priceMin: 120,
      priceMax: 250,
      category: "Hoppers",
      dietary: ["Vegetarian", "Gluten-Free"],
    },
    {
      name: "String Hoppers & Curry",
      desc: "Steamed rice noodle nests served with coconut milk curry and pol sambol",
      priceMin: 280,
      priceMax: 480,
      category: "Hoppers",
      dietary: ["Vegan", "Gluten-Free"],
    },
    {
      name: "Devilled Chicken",
      desc: "Crispy fried chicken tossed in spicy devilled sauce with capsicum and onion",
      priceMin: 700,
      priceMax: 1400,
      category: "Short Eats",
      dietary: ["Halal", "Spicy"],
    },
    {
      name: "Parippu (Dhal Curry)",
      desc: "Slow-cooked red lentil curry with tempered mustard seeds and curry leaves",
      priceMin: 200,
      priceMax: 350,
      category: "Rice & Curry",
      dietary: ["Vegan", "Gluten-Free"],
    },
    {
      name: "Watalappan",
      desc: "Traditional Sri Lankan steamed coconut custard with jaggery and cardamom",
      priceMin: 280,
      priceMax: 450,
      category: "Desserts",
      dietary: ["Vegetarian", "Gluten-Free"],
    },
    {
      name: "King Coconut Juice",
      desc: "Fresh thambili served straight from the coconut",
      priceMin: 150,
      priceMax: 280,
      category: "Beverages",
      dietary: ["Vegan", "Gluten-Free"],
    },
  ],
  Seafood: [
    {
      name: "Sri Lankan Mud Crab (kg)",
      desc: "Giant Sri Lankan mud crab cooked to your choice — black pepper, chilli, thermidor, or butter garlic",
      priceMin: 4500,
      priceMax: 9500,
      category: "Crab",
      dietary: ["Gluten-Free"],
    },
    {
      name: "Grilled Tiger Prawns",
      desc: "Jumbo tiger prawns grilled with herb butter and lemon, served with garlic aioli",
      priceMin: 2200,
      priceMax: 3800,
      category: "Prawns",
      dietary: ["Gluten-Free"],
    },
    {
      name: "Fish & Chips",
      desc: "Beer-battered local white fish with chunky fries, tartare sauce, and mushy peas",
      priceMin: 1200,
      priceMax: 1800,
      category: "Fish",
      dietary: [],
    },
    {
      name: "Lobster Thermidor",
      desc: "Sri Lankan spiny lobster in a classic thermidor sauce, grilled and flambéed",
      priceMin: 6500,
      priceMax: 12000,
      category: "Lobster",
      dietary: [],
    },
    {
      name: "Calamari Rings",
      desc: "Lightly battered squid rings with chipotle mayo and lime",
      priceMin: 950,
      priceMax: 1400,
      category: "Starters",
      dietary: [],
    },
    {
      name: "Seafood Platter (for 2)",
      desc: "Grilled crab, prawns, fish, squid, and mussels with three dipping sauces",
      priceMin: 5500,
      priceMax: 8500,
      category: "Grilled",
      dietary: ["Gluten-Free"],
    },
    {
      name: "Prawn Cocktail",
      desc: "Classic cold prawn cocktail with Marie Rose sauce on a bed of iceberg lettuce",
      priceMin: 1100,
      priceMax: 1600,
      category: "Starters",
      dietary: [],
    },
  ],
  Italian: [
    {
      name: "Spaghetti Carbonara",
      desc: "Al dente spaghetti with guanciale, egg yolk, pecorino romano, and black pepper",
      priceMin: 1400,
      priceMax: 2200,
      category: "Pasta",
      dietary: [],
    },
    {
      name: "Penne Arrabbiata",
      desc: "Penne in a spicy tomato and garlic sauce with fresh basil and chilli flakes",
      priceMin: 1100,
      priceMax: 1700,
      category: "Pasta",
      dietary: ["Vegan", "Spicy"],
    },
    {
      name: "Margherita Pizza",
      desc: "San Marzano tomato, fresh mozzarella di bufala, basil, extra virgin olive oil",
      priceMin: 1600,
      priceMax: 2400,
      category: "Pizza",
      dietary: ["Vegetarian"],
    },
    {
      name: "Pizza Diavola",
      desc: "Spicy salami, nduja, red onion, mozzarella, and chilli oil on a thin crust",
      priceMin: 1900,
      priceMax: 2800,
      category: "Pizza",
      dietary: ["Spicy"],
    },
    {
      name: "Beef Lasagne",
      desc: "Layers of slow-cooked beef bolognese, béchamel, and pasta, baked to golden perfection",
      priceMin: 1700,
      priceMax: 2500,
      category: "Pasta",
      dietary: [],
    },
    {
      name: "Tiramisu",
      desc: "Classic espresso-soaked ladyfingers layered with mascarpone cream and dusted with cocoa",
      priceMin: 800,
      priceMax: 1200,
      category: "Desserts",
      dietary: ["Vegetarian"],
    },
    {
      name: "Bruschetta al Pomodoro",
      desc: "Grilled sourdough topped with fresh tomato, garlic, basil, and aged balsamic",
      priceMin: 700,
      priceMax: 1100,
      category: "Antipasti",
      dietary: ["Vegan"],
    },
    {
      name: "Risotto ai Funghi",
      desc: "Creamy arborio rice with wild mushrooms, truffle oil, and aged parmesan",
      priceMin: 1600,
      priceMax: 2400,
      category: "Risotto",
      dietary: ["Vegetarian"],
    },
  ],
  Japanese: [
    {
      name: "Salmon Sashimi (6 pcs)",
      desc: "Premium Norwegian salmon, sliced to order, served with wasabi and pickled ginger",
      priceMin: 1800,
      priceMax: 2800,
      category: "Sashimi",
      dietary: ["Gluten-Free"],
    },
    {
      name: "Dragon Roll (8 pcs)",
      desc: "Prawn tempura, cucumber, topped with avocado and unagi sauce",
      priceMin: 2200,
      priceMax: 3200,
      category: "Sushi",
      dietary: [],
    },
    {
      name: "Tonkotsu Ramen",
      desc: "Rich pork bone broth with chashu pork, soft-boiled egg, nori, and bamboo shoots",
      priceMin: 1600,
      priceMax: 2400,
      category: "Ramen",
      dietary: [],
    },
    {
      name: "Chicken Katsu Curry",
      desc: "Panko-crusted chicken with Japanese curry sauce, steamed rice, and pickles",
      priceMin: 1400,
      priceMax: 2000,
      category: "Mains",
      dietary: [],
    },
    {
      name: "Edamame",
      desc: "Steamed salted young soybeans — the perfect starter",
      priceMin: 450,
      priceMax: 700,
      category: "Starters",
      dietary: ["Vegan", "Gluten-Free"],
    },
    {
      name: "Beef Teppanyaki",
      desc: "Australian wagyu beef cooked on the hot plate with garlic fried rice and seasonal vegetables",
      priceMin: 4500,
      priceMax: 7000,
      category: "Teppanyaki",
      dietary: [],
    },
    {
      name: "Miso Soup",
      desc: "Traditional dashi miso with tofu, wakame, and spring onion",
      priceMin: 350,
      priceMax: 550,
      category: "Soups",
      dietary: ["Vegan"],
    },
    {
      name: "Matcha Ice Cream",
      desc: "Creamy ceremonial grade matcha ice cream",
      priceMin: 600,
      priceMax: 900,
      category: "Desserts",
      dietary: ["Vegetarian", "Gluten-Free"],
    },
  ],
  Indian: [
    {
      name: "Chicken Tikka Masala",
      desc: "Tender chicken tikka in a rich, creamy tomato-based masala sauce",
      priceMin: 1100,
      priceMax: 1800,
      category: "Curries",
      dietary: ["Halal"],
    },
    {
      name: "Dal Makhani",
      desc: "Slow-cooked black lentils and kidney beans in a buttery tomato sauce",
      priceMin: 850,
      priceMax: 1300,
      category: "Curries",
      dietary: ["Vegetarian"],
    },
    {
      name: "Lamb Biryani",
      desc: "Fragrant basmati rice layered with slow-cooked spiced lamb, saffron, and fried onions",
      priceMin: 1500,
      priceMax: 2500,
      category: "Biryani",
      dietary: ["Halal"],
    },
    {
      name: "Garlic Naan",
      desc: "Soft leavened bread brushed with garlic butter, baked in a clay tandoor",
      priceMin: 200,
      priceMax: 350,
      category: "Breads",
      dietary: ["Vegetarian"],
    },
    {
      name: "Seekh Kebab",
      desc: "Minced lamb and herb kebabs cooked in the tandoor, served with mint chutney",
      priceMin: 1200,
      priceMax: 1800,
      category: "Tandoor",
      dietary: ["Halal"],
    },
    {
      name: "Paneer Butter Masala",
      desc: "Soft cottage cheese cubes in a velvety tomato and cashew sauce",
      priceMin: 1000,
      priceMax: 1600,
      category: "Curries",
      dietary: ["Vegetarian"],
    },
    {
      name: "Gulab Jamun",
      desc: "Soft milk dumplings soaked in rose-flavoured sugar syrup, served warm",
      priceMin: 400,
      priceMax: 650,
      category: "Desserts",
      dietary: ["Vegetarian"],
    },
    {
      name: "Mango Lassi",
      desc: "Blended yoghurt and alphonso mango with a hint of cardamom",
      priceMin: 350,
      priceMax: 550,
      category: "Beverages",
      dietary: ["Vegetarian", "Gluten-Free"],
    },
  ],
  Continental: [
    {
      name: "Beef Tenderloin (200g)",
      desc: "Grass-fed beef tenderloin, cooked to your preference, with red wine jus and seasonal vegetables",
      priceMin: 3500,
      priceMax: 6000,
      category: "Steaks",
      dietary: ["Gluten-Free"],
    },
    {
      name: "Caesar Salad",
      desc: "Romaine lettuce, parmesan, house-made Caesar dressing, anchovies, and garlic croutons",
      priceMin: 900,
      priceMax: 1400,
      category: "Salads",
      dietary: [],
    },
    {
      name: "French Onion Soup",
      desc: "Caramelised onion broth topped with a crouton and melted gruyère",
      priceMin: 850,
      priceMax: 1300,
      category: "Soups",
      dietary: ["Vegetarian"],
    },
    {
      name: "Chicken Cordon Bleu",
      desc: "Stuffed chicken breast with ham and Swiss cheese, pan-fried golden, with Dijon sauce",
      priceMin: 2200,
      priceMax: 3200,
      category: "Mains",
      dietary: [],
    },
    {
      name: "Crème Brûlée",
      desc: "Silky vanilla custard with a perfectly caramelised sugar crust",
      priceMin: 700,
      priceMax: 1100,
      category: "Desserts",
      dietary: ["Vegetarian", "Gluten-Free"],
    },
    {
      name: "Mushroom Velouté",
      desc: "Silky wild mushroom soup with truffle cream and chives",
      priceMin: 750,
      priceMax: 1200,
      category: "Soups",
      dietary: ["Vegetarian"],
    },
  ],
  Chinese: [
    {
      name: "Dim Sum Basket (4 pcs)",
      desc: "Assorted steamed dumplings — har gow, siu mai, char siu bao, and cheung fun",
      priceMin: 650,
      priceMax: 1100,
      category: "Dim Sum",
      dietary: [],
    },
    {
      name: "Beef Chow Mein",
      desc: "Stir-fried egg noodles with tender beef strips, beansprouts, and oyster sauce",
      priceMin: 900,
      priceMax: 1500,
      category: "Noodles",
      dietary: [],
    },
    {
      name: "Kung Pao Chicken",
      desc: "Diced chicken with peanuts, dried chillies, and Sichuan pepper in a tangy sauce",
      priceMin: 1100,
      priceMax: 1700,
      category: "Rice",
      dietary: ["Spicy", "Gluten-Free"],
    },
    {
      name: "Peking Duck (half)",
      desc: "Crispy skin Peking duck served with pancakes, spring onion, cucumber, and hoisin sauce",
      priceMin: 3200,
      priceMax: 5000,
      category: "Seafood",
      dietary: [],
    },
    {
      name: "Hot & Sour Soup",
      desc: "Classic Cantonese hot and sour soup with tofu, mushrooms, and egg ribbons",
      priceMin: 550,
      priceMax: 850,
      category: "Soups",
      dietary: ["Vegetarian", "Spicy"],
    },
    {
      name: "Egg Fried Rice",
      desc: "Wok-tossed jasmine rice with egg, spring onion, and light soy sauce",
      priceMin: 600,
      priceMax: 950,
      category: "Rice",
      dietary: ["Vegetarian"],
    },
    {
      name: "Mango Pudding",
      desc: "Chilled silken mango pudding with evaporated milk and fresh mango",
      priceMin: 450,
      priceMax: 700,
      category: "Vegetarian",
      dietary: ["Vegan", "Gluten-Free"],
    },
  ],
  "BBQ & Grill": [
    {
      name: "Half Rack Pork Ribs",
      desc: "Slow-smoked pork ribs with house BBQ sauce, coleslaw, and cornbread",
      priceMin: 2800,
      priceMax: 4200,
      category: "Pork",
      dietary: [],
    },
    {
      name: "BBQ Chicken Platter",
      desc: "Half chicken marinated in smoky BBQ rub, grilled over charcoal, served with garlic bread",
      priceMin: 1800,
      priceMax: 2800,
      category: "Chicken",
      dietary: ["Halal"],
    },
    {
      name: "Smash Burger",
      desc: "Double smashed beef patty, American cheese, pickles, caramelised onion, house sauce on a brioche bun",
      priceMin: 1400,
      priceMax: 2000,
      category: "Beef",
      dietary: [],
    },
    {
      name: "Lamb Chops (3 pcs)",
      desc: "French-trimmed lamb cutlets marinated in rosemary and garlic, grilled medium-rare",
      priceMin: 3200,
      priceMax: 4800,
      category: "Lamb",
      dietary: ["Gluten-Free", "Halal"],
    },
    {
      name: "Loaded Nachos",
      desc: "Tortilla chips with melted cheese, jalapeños, guacamole, sour cream, and pico de gallo",
      priceMin: 900,
      priceMax: 1400,
      category: "Starters",
      dietary: ["Vegetarian"],
    },
    {
      name: "Mac & Cheese",
      desc: "Creamy three-cheese sauce on al dente macaroni, baked with a panko crust",
      priceMin: 700,
      priceMax: 1100,
      category: "Sides",
      dietary: ["Vegetarian"],
    },
  ],
};
